slug: the-prompting-playbook
video_id: G2B0YWuJUgI
title: "The prompting playbook"
url: https://www.youtube.com/watch?v=G2B0YWuJUgI
upload_date: 
duration_seconds: 2029
duration_human: 33:49
transcribed_at: 2026-05-25T11:24:50+00:00
